config/routes.rb
Rails.application.routes.draw do
  
  get 'cars' => 'cars#index'

  get 'cars/new'

  get 'cars/delete'

  get 'cars/update'

  get 'cars/show'

  get 'sessions/new'

  get 'users/new'

  get 'users/update'

  get 'users/delete'

  root 'static_pages#home'

  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/policy'

  get 'charging' => 'users#charging'
  
  get 'about' => 'static_pages#about'

  get 'policy' => 'static_pages#policy'

  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  
  post   'login'   => 'sessions#create'

  delete 'logout'  => 'sessions#destroy'
  
   resources :users

    
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
 
  def index
    @cars = Car.all
  end

  def new
	  	 @car = Car.new
    end

  def delete
  end

  def update
  end

  def show
  end


    def create
	    @car = Car.new(car_params)
	    if @car.save
	      flash[:success] = "Car added to database"
	      redirect_to root_url
	    else
	      render 'new'
	    end
  	end

  private

    def car_params
      params.require(:car).permit(:type, :lat, :lng)
    end

  
  
end

app/controllers/sessions_controller.rb
include SessionsHelper

class SessionsController < ApplicationController

  def new
  end

 def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  	@carsAtt= Car.all 
  end

  def about
  end

  def policy
  end

  def login
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	 @user = User.new
  end

  def update
  end

  def delete
  end

  def charging
  end

  def show
    @user = User.find(params[:id])
  end
  
   def create
    @user = User.new(user_params)
    #user[:charg] = 1000
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email,:charg, :password,:password_confirmation)
    end

    def chargParams
      params.require(:userSharg).permit(:id,:name,:charg)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "سامانه خودرو پارک شباهنگ"
    if page_title.empty?
      base_title
    else
      page_title
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

 # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end


   # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    #forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

   # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/delete.html.erb
<h1>Cars#delete</h1>
<p>Find me in app/views/cars/delete.html.erb</p>

app/views/cars/index.html.erb
<% provide(:title, 'All Cars') %>
<h1>All Cars</h1>

<ul class="cars">
  <% @cars.each do |car| %>
    <li>
    <%=  car.id %> -   <%=  car.carType %>  
    <br>
     <%=  car.lng %> <%=  car.lat %> 
    </li>
  <% end %>
</ul>

app/views/cars/new.html.erb
<h1>Cars#new</h1>
<p>Find me in app/views/cars/new.html.erb</p>

app/views/cars/show.html.erb
<h1>Cars#show</h1>
<p>Find me in app/views/cars/show.html.erb</p>

app/views/cars/update.html.erb
<h1>Cars#update</h1>
<p>Find me in app/views/cars/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 

  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
</head>
<body>
 
  <table id="main_table" border="0" cellpadding="0" cellspacing="0" class="main_table">
	 <tr>
		 <td id="menu_col" class="menu_col">
		
		 	<table>
		 		<tr>
		 			<%= link_to image_tag("sidebarPic.jpg", alt: "Home"),'../' %>
		 		
		 			<td class="sidebarItem">
		 				 
		 				 <% if logged_in? %>	
							<div class="sidebarMenuImage"><%= image_tag('edit profile.jpg', :class => "sidebarMenuImage") %></div>	
							<div class="sidebarText"><a class="sidebarText" href="../users/<%= @current_user[:id] %>"><%= @current_user[:name] %> خوش آمدید</a></div>

							<div class="sidebarMenuImage"><%= image_tag('dollar.png', :class => "sidebarMenuImage") %></div>
				 			<div class="sidebarText"><a class="sidebarText" href="charging">افزایش اعتبار</a></div>
						<% else %>

							<div class="sidebarMenuImage"><%= image_tag('log in.jpg', :class => "sidebarMenuImage") %></div>

							<div class="sidebarText"><a class="sidebarText" href="<%= login_path %>">ورود</a></div>		 				

							
						<% end %>

		 				<div class="sidebarMenuImage"><%= image_tag('policy.png', :class => "sidebarMenuImage") %></div>
			 			<div class="sidebarText"><a class="sidebarText" href="<%= policy_path %>">قوانین</a></div>

			 			<div class="sidebarMenuImage"><%= image_tag('about.png', :class => "sidebarMenuImage") %></div>
			 			<div class="sidebarText"><a class="sidebarText" href="<%= about_path %>">درباره ما</a></div>

			 			 <% if logged_in? %>
			 				
			 				<div class="sidebarMenuImage"><%= image_tag('Log Off.jpg', :class => "sidebarMenuImage") %></div>
			 			 	<div class="sidebarText"><%= link_to "خروج", logout_path, method: :delete ,:class => "sidebarText" %></div>
			 			 <% end %>

		 			</td>
		 		</tr>
		 	</table>
		 	
		 	
		 </td> 
		 <td id="content_col"> <!— main content-->

		 	
		 <div class="header"><%= full_title(yield(:title)) %></div>

		 	<div >
		 		<%= yield %>
			</div>
		 </td>
	 </tr>

	</table>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'درباره ما') %>

<div class="MainAbout"  >
<div id="AbPic" >
</div>
<div id="AbPic2"  >
</div>
    <div id="AbPic3"  >
</div>
<div id="Abcontext"   >
<p class="TxtP">

 سامانه ی خودرو شباهنگ از دی ماه سال 1393 کار خود را آغاز کرد
این سامانه به منظور راحتی مشتریان خود این امکان را فراهم کرده است که مشتری پس از ثبت نام قادر به یافتن خودرو هایی که در نزدیکترین نقطه به او هستند باشد
و پس از مشاهده ی مکان خودرو به آن مراجعه کرده و از آن استفاده کند
    <br />

شماره های تماس : 77 77 442 021
        <br />
 ایمیل : shabahang@ut.ac.ir

</p>
</div>

</div>

app/views/static_pages/home.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyB5gi1C4t7kUuRsAYOSNNvi0wcPDauVkJU &sensor=false&libraries=places,geometry ">
</script>

<script>
  function initialize() {
  var mapCanvas = document.getElementById('map-canvas');
   var myLatlng = new google.maps.LatLng(35.696208750953396, 51.4229491353035);
   var mapOptions = {
           zoom: 14,
       center: myLatlng,

      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(mapCanvas , mapOptions);

    var image = '../img/car_1.png';

    var car1latlng = new google.maps.LatLng(35.706623077392580, 51.411830902099610);
	 var marker = new google.maps.Marker({
      position: car1latlng,
      map: map,
      title: 'prid',
      icon: image

  });

   var car2latlng = new google.maps.LatLng(35.702335357666016, 51.412712097167970);
   var marker = new google.maps.Marker({
      position: car2latlng,
      map: map,
      title: 'samand',
      icon: image

  });

  
  }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="map-canvas"></div>

<ul class="cars">
  <% @carsAtt.each do |car| %>
    <li>
    <%=  car.id %> -   <%=  car.carType %>  
    <br>
     <%=  car.lng %> <%=  car.lat %> 
    </li>
  <% end %>
</ul>

app/views/static_pages/login.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in Now", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now! dsadsad", signup_path %></p>
  </div>
</div>

app/views/static_pages/policy.html.erb
<% provide(:title, 'قوانین') %>

<div class="MainLow">
<div id="LPic"  >
</div>
   
<div id="Lcontext"   >
<p class="TxtLow">

 
 ضمن تبریک وتشکر به دلیل انتخاب شایسته تان
 سامانه خودرو یاب شباهنگ برای راحتی استفاده شما قوانین زیر را در نظر گرفته است:
 <br/>
 <br/>
 <br/>
 1-برای استفاده از امکانات این سامانه حتما در سایت عضو شوید
  <br/>
  2-پس از عضویت و شارژ حساب خود قادر خواهید بود از تمامی امکانات این سامانه استفاده کنید
   <br/>
   3-افرادی که از این سامانه استفاده کرده و عضویت آن را میپذیرند حتما باید دارای گواهینامه باشند
    <br/>
    4-پس از انتخاب خودروی مورد نظر تا حداکثر 30 دقیقه مهلت دارید تا خود را به خودروی مورد نظر برسانید در  غیر اینصورت از حساب شما مبلغی کسر شده و خودرو به مشتری بعدی تحویل میشود. <br/><br/><br/>
   <br/>
 از انتخاب شما متشکریم
 <br/>

    مدیریت سامانه خودرو بارک شباهنگ
 </p>
</div>


</div>

app/views/users/charging.html.erb
<% provide(:title, 'افزایش اعتبار') %>

<%= params %>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'ثبت نام') %>
<br>
<br>
<br>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "ساخت حساب", class: "btn shabahangBtn" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "مشخصات حساب کاربری") %>
<br>

<div class="infoField">نام : </div><div class="infoValue"><%= @user.name %></div>

<br>

<div class="infoField">ایمیل : </div><div class="infoValue"><%= @user.email %></div>

<br>

<div class="infoField">شارژ حساب : </div><div class="infoValue chargValue"><%= @user.charg %></div>

<br>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>